---
schema:
  procedures: {}
  tables:
    records:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - record_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        record_id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: record_id
          order: 1
          size:
            - 0
        string:
          data_type: char
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: string
          order: 2
          size:
            - 255
      indices: []
      name: records
      options: []
      order: 1
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Record
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
